name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:  #  Use DATABASE_URL from GitHub Secrets
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"

      - name: Install Goose for Migrations
        run: go install github.com/pressly/goose/v3/cmd/goose@latest  #  Install goose

      - name: Build Production App
        run: scripts/buildprod.sh

      #  Step 1: Authenticate with GCP
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      #  Step 2: Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: notely-451204

      #  Step 3: Authenticate Docker with Google Artifact Registry
      - name: Configure Docker to use Google Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      #  Step 4: Build & Push Docker Image to Artifact Registry
      - name: Build and Push Docker Image
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-451204/notely-ar-repo/notely:latest .

      #  Step 5: Run Database Migrations Before Deploying
      - name: Run Database Migrations (if exists)
        run: |
          if [ -d "migrations" ]; then
            goose -dir migrations postgres "$DATABASE_URL" up
          else
            echo "No migrations directory found. Skipping migrations."
          fi

      #  Step 6: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy notely \
            --image us-central1-docker.pkg.dev/notely-451204/notely-ar-repo/notely:latest \
            --region us-central1 \
            --allow-unauthenticated \
            --project notely-451204 \
            --max-instances=4